#!/usr/bin/env node
/* Regenerates parse-extract.js by slicing parseHebrewData (+deps) out of
 * ../server/server.js. Keeps the unit test honest: it always tests the REAL
 * server code, not a hand-copied duplicate. Run: node tests/extract-parse.js */
const fs = require('fs'), path = require('path');
const src = fs.readFileSync(path.join(__dirname, '..', 'server', 'server.js'), 'utf8').replace(/\r\n/g, '\n');
const lines = src.split('\n');
const slc = (a, b) => lines.slice(a - 1, b).join('\n');
const findLine = (needle, from = 1) => {
  for (let i = from; i <= lines.length; i++) if (lines[i - 1].includes(needle)) return i;
  return -1;
};
const charMap = findLine('const CHAR_MAP = {');
const getCss  = findLine('function getCssClass(');
const parseFn = findLine('function parseHebrewData(');
let end = -1;
// Window was 700 lines; parseHebrewData has grown past that (873 lines as of
// the "harden the tokens" pass that added the baked-modification safety net),
// so the scan silently found no "return output;" in range, `end` stayed -1,
// and the slice came out EMPTY — every consumer then died with
// "parseHebrewData is not defined". Widened with headroom for future growth;
// there IS a second, unrelated "return output;" further down the file (a
// different top-level function), so this window must stay short enough not
// to reach it — 1500 lines comfortably covers parseHebrewData alone.
for (let i = parseFn; i < parseFn + 1500; i++) if (lines[i - 1].trim() === 'return output;') { end = i + 1; break; }
// parseHebrewData calls loadLexicons(), which lives well past the search
// window above (it's a standalone helper, not nested inside parseHebrewData) — it
// was missing entirely, so any test path that reached it died with
// "loadLexicons is not defined". Slice it out too, along with the _lexiconCache
// variable it closes over.
const lexCacheDecl = findLine('let _lexiconCache = null;');
const loadLexFn    = findLine('function loadLexicons(');
let loadLexEnd = -1;
for (let i = loadLexFn; i < loadLexFn + 100; i++) if (lines[i - 1] === '}') { loadLexEnd = i; break; }
// parseHebrewData's own per-word flush pushes a 'lemmaTranslit' field computed
// via nameTranslit(strongs, trueRoot) (the Har-Al/Yashar-Al hyphenated-name
// spelling override). nameTranslit lives far below the 1500-line parseHebrewData
// window (compound-name/hyphenation code, added long after this extractor was
// first written) and was missing entirely — any word with a resolved root threw
// "nameTranslit is not defined" the moment it ran outside the full server.js
// process. Slice it + its two small dependencies (normSn, hyphenAllowlist +
// its HYPHEN_ALLOW_PATH/_hyphenAllow state) the same targeted way as loadLexicons
// above, rather than widening the main parseFn window to reach them.
const normSnDecl     = findLine("const normSn = (sn) =>");
let normSnEnd = -1;
for (let i = normSnDecl; i < normSnDecl + 5; i++) if (lines[i - 1].trim().endsWith(';')) { normSnEnd = i; break; }
const hyphenPathDecl = findLine('const HYPHEN_ALLOW_PATH =');
const nameTranslitFn = findLine('function nameTranslit(');
let nameTranslitEnd = -1;
// nameTranslit + hyphenAllowlist are two short, adjacent functions — find the
// close of the SECOND one (hyphenAllowlist), not the first, so both come along.
for (let i = nameTranslitFn; i < nameTranslitFn + 40; i++) {
  if (lines[i - 1] === '}' && findLine('function hyphenAllowlist(', nameTranslitFn) > 0
      && i >= findLine('function hyphenAllowlist(', nameTranslitFn)) { nameTranslitEnd = i; break; }
}
const out = [
  '// AUTO-GENERATED by tests/extract-parse.js — do not edit. Slices the REAL server parseHebrewData.',
  "const fs = require('fs'); const path = require('path');",
  slc(charMap, getCss - 1),
  slc(getCss, parseFn - 1),
  slc(parseFn, end + 1),
  (lexCacheDecl > 0 && loadLexFn > 0 && loadLexEnd > 0) ? slc(lexCacheDecl, loadLexEnd) : '',
  (normSnDecl > 0 && normSnEnd > 0) ? slc(normSnDecl, normSnEnd) : '',
  (hyphenPathDecl > 0 && nameTranslitFn > 0 && nameTranslitEnd > 0) ? slc(hyphenPathDecl, nameTranslitEnd) : '',
  'module.exports = { parseHebrewData };',
].join('\n');
fs.writeFileSync(path.join(__dirname, 'parse-extract.cjs'), out);
console.log('Wrote tests/parse-extract.cjs from server/server.js');
